Update validation.yml

diff --git a/validation.yml b/validation.yml
--- a/validation.yml
+++ b/validation.yml
@@ -75,6 +75,16 @@
         msg: "Skipping primary index creation as the following indexes were found: {{ primary_index_names }}"
       when: primary_index_names | length > 0
 
+    - name: Validate index scope and collection are not '_default'
+      shell: |
+        if echo "{{ item }}" | grep -qE 'scope:\s*_default|collection:\s*_default'; then
+          echo "Error: Index creation in '_default' scope or collection is not allowed!" && exit 1
+        fi
+      with_items: "{{ index_creation_statements }}"
+      register: check_default_scope_and_collection
+      failed_when: check_default_scope_and_collection.rc != 0  # Fail the task if '_default' scope or collection is detected
+      when: item is defined and item != ""  # Ensure there is an item to check
+
     - name: Validate index scope is not '_default'
       shell: |
         if echo "{{ item }}" | grep -q 'scope:\s*_default'; then
@@ -85,15 +95,7 @@
       failed_when: check_default_scope.rc != 0  # Fail the task if '_default' scope is detected
       when: item is defined and item != ""  # Ensure there is an item to check
 
-    - name: Validate index scope and collection are not '_default'
-      shell: |
-        if echo "{{ item }}" | grep -qE 'scope:\s*_default|collection:\s*_default'; then
-          echo "Error: Index creation in '_default' scope or collection is not allowed!" && exit 1
-        fi
-      with_items: "{{ index_creation_statements }}"
-      register: check_default_scope_and_collection
-      failed_when: check_default_scope_and_collection.rc != 0  # Fail the task if '_default' scope or collection is detected
-      when: item is defined and item != ""  # Ensure there is an item to check
+    
 
 
 
