Update validation.yml

diff --git a/validation.yml b/validation.yml
--- a/validation.yml
+++ b/validation.yml
@@ -66,6 +66,16 @@
       set_fact:
         file_data: "{{ file_contents['content'] | b64decode }}"
 
+    - name: Validate index scope is not '_default'
+      shell: |
+        if echo "{{ item }}" | grep -q 'scope:\s*_default'; then
+          echo "Error: Index creation in '_default' scope is not allowed!" && exit 1
+        fi
+      with_items: "{{ index_creation_statements }}"
+      register: check_default_scope
+      failed_when: check_default_scope.rc != 0  # Fail the task if '_default' scope is detected
+      when: item is defined and item != ""  # Ensure there is an item to check
+
     # Extract primary index names using regex
     - name: Extract primary index names using regex
       set_fact:
@@ -79,13 +89,6 @@
       debug:
         msg: "Skipping primary index creation as the following indexes were found: {{ primary_index_names }}"
       when: primary_index_names | length > 0
-
-    - name: Create primary index
-      shell: "/opt/couchbase/bin/cbq -u Admin -p redhat -s '{{ item }}'"
-      with_items: "{{ primary_index_creation_statements }}"
-      ignore_errors: true
-      register: ddl_output
-      when: primary_index_names | length == 0
 
     # Decode file contents (if it's base64 encoded)
     - name: Decode file contents
