Update validation.yml

diff --git a/validation.yml b/validation.yml
--- a/validation.yml
+++ b/validation.yml
@@ -18,6 +18,16 @@
         src: /home/ubuntu/Couchbase_UPS/index_file.txt
       register: index_file_content
 
+    - name: Validate index scope is not '_default'
+      shell: |
+        if echo "{{ item }}" | grep -q 'scope:\s*_default'; then
+          echo "Error: Index creation in '_default' scope is not allowed!" && exit 1
+        fi
+      with_items: "{{ index_creation_statements }}"
+      register: check_default_scope
+      failed_when: check_default_scope.rc != 0  # Fail the task if '_default' scope is detected
+      when: item is defined and item != ""  # Ensure there is an item to check
+
     - name: Decode the index file content
       set_fact:
         decoded_index_file_content: "{{ index_file_content.content | b64decode }}"
@@ -60,15 +70,7 @@
       set_fact:
         file_data: "{{ file_content.content | b64decode | string }}"
 
-    - name: Validate index scope is not '_default'
-      shell: |
-        if echo "{{ item }}" | grep -q 'scope:\s*_default'; then
-          echo "Error: Index creation in '_default' scope is not allowed!" && exit 1
-        fi
-      with_items: "{{ index_creation_statements }}"
-      register: check_default_scope
-      failed_when: check_default_scope.rc != 0  # Fail the task if '_default' scope is detected
-      when: item is defined and item != ""  # Ensure there is an item to check
+    
  
 
       # Extract primary index names using regex
