Update validation.yml

diff --git a/validation.yml b/validation.yml
--- a/validation.yml
+++ b/validation.yml
@@ -75,10 +75,12 @@
         
     - name: Validate index scope is not '_default'
       shell: |
-        echo "{{ item }}" | grep -q 'scope:default'
+        if echo "{{ item }}" | grep -q 'scope:\s*_default'; then
+          echo "Error: Index creation in '_default' scope is not allowed!" && exit 1
+        fi
       with_items: "{{ index_creation_statements }}"
       register: check_default_scope
-      failed_when: check_default_scope.rc == 0
+      failed_when: check_default_scope.rc != 0  # Fail the task if '_default' scope is detected
       when: item is defined and item != ""  # Ensure there is an item to check
 
     - name: Create indexes
